# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6a1df2739ae719e88be046617d9e69ad4b5849bcd1517fad55e8909868a0eb23ccdf010f81af9704cb9777aac6bba72e5057526e3591542428d0088083b0b47

test:
  secret_key_base: a8b59762d8a178d55dd380e3f33ffbd045a41d0f4734fdc5da3fb36e999759ca84ef8f51885ccc3c0b4146255bb9c042277200d80a5f64e15264e14cb4639b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
